/* 캐주얼 킹덤러쉬/랜덤다이스 톤 — 아트팩 + 100스테이지 데이터 */
window.DKCONTENT = (function () {
  const maps = [
    { key: 'cMap1', src: 'casual/maps/map-01-meadow.jpg', name: '꽃초원' },
    { key: 'cMap2', src: 'casual/maps/map-02-candy.jpg', name: '사탕숲' },
    { key: 'cMap3', src: 'casual/maps/map-03-beach.jpg', name: '햇살해변' },
    { key: 'cMap4', src: 'casual/maps/map-04-snow.jpg', name: '눈마을' },
    { key: 'cMap5', src: 'casual/maps/map-05-autumn.jpg', name: '호박농장' },
    { key: 'cMap6', src: 'casual/maps/map-06-night.jpg', name: '달빛버섯' },
    { key: 'cMap7', src: 'casual/maps/map-07-volcano.jpg', name: '장난화산' },
    { key: 'cMap8', src: 'casual/maps/map-08-sakura.jpg', name: '벚꽃언덕' },
    { key: 'cMap9', src: 'casual/maps/map-09-desert.jpg', name: '오아시스' },
    { key: 'cMap10', src: 'casual/maps/map-10-bamboo.jpg', name: '대나무도장' },
    { key: 'cMap11', src: 'casual/maps/map-11-swamp.jpg', name: '연꽃늪' },
    { key: 'cMap12', src: 'casual/maps/map-12-crystal.jpg', name: '무지개광산' },
    { key: 'cMap13', src: 'casual/maps/map-13-clock.jpg', name: '태엽골짜기' },
    { key: 'cMap14', src: 'casual/maps/map-14-coral.jpg', name: '산호초' },
    { key: 'cMap15', src: 'casual/maps/map-15-haunt.jpg', name: '사탕묘지' },
    { key: 'cMap16', src: 'casual/maps/map-16-honey.jpg', name: '꿀초원' },
    { key: 'cMap17', src: 'casual/maps/map-17-cloud.jpg', name: '구름선디' },
    { key: 'cMap18', src: 'casual/maps/map-18-academy.jpg', name: '마법학원' },
    { key: 'cMap19', src: 'casual/maps/map-19-pirate.jpg', name: '해적만' },
    { key: 'cMap20', src: 'casual/maps/map-20-sunflower.jpg', name: '해바라기밭' },
    { key: 'cMap21', src: 'casual/maps/map-21-moon.jpg', name: '달치즈촌' },
    { key: 'cMap22', src: 'casual/maps/map-22-rain.jpg', name: '비마을' },
    { key: 'cMap23', src: 'casual/maps/map-23-workshop.jpg', name: '장난감공방' },
    { key: 'cMap24', src: 'casual/maps/map-24-onsen.jpg', name: '온천마을' },
    { key: 'cMap25', src: 'casual/maps/map-25-gingerbread.jpg', name: '진저브레드' },
    { key: 'cMap26', src: 'casual/maps/map-26-maple.jpg', name: '단풍협곡' },
    { key: 'cMap27', src: 'casual/maps/map-27-aurora.jpg', name: '오로라툰드라' },
    { key: 'cMap28', src: 'casual/maps/map-28-toadstool.jpg', name: '버섯초원' },
    { key: 'cMap29', src: 'casual/maps/map-29-mesa.jpg', name: '메사협곡' },
    { key: 'cMap30', src: 'casual/maps/map-30-firefly.jpg', name: '반딧불숲' },
    { key: 'cMap31', src: 'casual/maps/map-31-carnival.jpg', name: '서커스장' },
    { key: 'cMap32', src: 'casual/maps/map-32-vineyard.jpg', name: '포도언덕' },
    { key: 'cMap33', src: 'casual/maps/map-33-icelake.jpg', name: '얼음호수' },
    { key: 'cMap34', src: 'casual/maps/map-34-jungle.jpg', name: '정글유적' },
    { key: 'cMap35', src: 'casual/maps/map-35-tulip.jpg', name: '튤립풍차' },
    { key: 'cMap36', src: 'casual/maps/map-36-crystalcity.jpg', name: '밤수정도시' },
    { key: 'cMap37', src: 'casual/maps/map-37-lavender.jpg', name: '라벤더밭' },
    { key: 'cMap38', src: 'casual/maps/map-38-halloween.jpg', name: '할로윈마을' },
    { key: 'cMap39', src: 'casual/maps/map-39-bioreef.jpg', name: '야광산호' },
    { key: 'cMap40', src: 'casual/maps/map-40-alpine.jpg', name: '알프스마을' },
    { key: 'cMap41', src: 'casual/maps/map-41-rice.jpg', name: '계단식논' },
    { key: 'cMap42', src: 'casual/maps/map-42-nightdesert.jpg', name: '밤오아시스' },
    { key: 'cMap43', src: 'casual/maps/map-43-nightclock.jpg', name: '밤태엽도시' },
    { key: 'cMap44', src: 'casual/maps/map-44-fairy.jpg', name: '요정공터' },
    { key: 'cMap45', src: 'casual/maps/map-45-harbor.jpg', name: '어촌항구' },
    { key: 'cMap46', src: 'casual/maps/map-46-nightbamboo.jpg', name: '밤대나무' },
    { key: 'cMap47', src: 'casual/maps/map-47-candyspace.jpg', name: '사탕우주' },
    { key: 'cMap48', src: 'casual/maps/map-48-orchard.jpg', name: '사과과수원' },
    { key: 'cMap49', src: 'casual/maps/map-49-lavabeach.jpg', name: '용암해변' },
    { key: 'cMap50', src: 'casual/maps/map-50-royal.jpg', name: '왕실정원' },
  ];
  const skin = (f, letter) => ({ key: `cT${f}${letter}`, src: `casual/towers/t${f}-${letter}.png` });
  const towerSkins = {
    1: [skin(1, 'a'), skin(1, 'b'), skin(1, 'c'), skin(1, 'd'), skin(1, 'e')],
    2: [skin(2, 'a'), skin(2, 'b'), skin(2, 'c'), skin(2, 'd'), skin(2, 'e')],
    3: [skin(3, 'a'), skin(3, 'b'), skin(3, 'c'), skin(3, 'd'), skin(3, 'e')],
    4: [skin(4, 'a'), skin(4, 'b'), skin(4, 'c'), skin(4, 'd'), skin(4, 'e')],
    5: [skin(5, 'a'), skin(5, 'b'), skin(5, 'c'), skin(5, 'd'), skin(5, 'e')],
    6: [skin(6, 'a'), skin(6, 'b'), skin(6, 'c'), skin(6, 'd'), skin(6, 'e')],
  };
  const bases = [
    { id: 'slime', name: '슬라임', hp: 28, speed: 50, gold: 5, dmg: 1, size: 40, move: 'ground', sprite: 'cSlime', src: 'casual/enemies/slime.png' },
    { id: 'shroom', name: '버섯돌이', hp: 36, speed: 42, gold: 6, dmg: 1, size: 44, move: 'ground', sprite: 'cShroom', src: 'casual/enemies/shroom.png' },
    { id: 'pig', name: '돼지산적', hp: 48, speed: 46, gold: 7, dmg: 1, size: 48, move: 'ground', sprite: 'cPig', src: 'casual/enemies/pig.png' },
    { id: 'chicken', name: '닭기사', hp: 40, speed: 62, gold: 7, dmg: 1, size: 46, move: 'ground', sprite: 'cChicken', src: 'casual/enemies/chicken.png' },
    { id: 'goblin', name: '고블린', hp: 34, speed: 70, gold: 8, dmg: 1, size: 44, move: 'ground', sprite: 'cGoblin', src: 'casual/enemies/goblin.png' },
    { id: 'sheep', name: '양기사', hp: 52, speed: 44, gold: 8, dmg: 1, size: 48, move: 'ground', sprite: 'cSheep', src: 'casual/enemies/sheep.png' },
    { id: 'cactus', name: '선인장카우보이', hp: 46, speed: 48, gold: 8, dmg: 1, size: 46, move: 'ground', sprite: 'cCactus', src: 'casual/enemies/cactus.png' },
    { id: 'fox', name: '여우도둑', hp: 32, speed: 78, gold: 9, dmg: 1, size: 44, move: 'ground', sprite: 'cFox', src: 'casual/enemies/fox.png' },
    { id: 'penguin', name: '펭귄눈뭉치', hp: 38, speed: 50, gold: 7, dmg: 1, size: 44, move: 'ground', sprite: 'cPenguin', src: 'casual/enemies/penguin.png' },
    { id: 'raccoon', name: '너구리닌자', hp: 36, speed: 80, gold: 9, dmg: 1, size: 44, move: 'ground', sprite: 'cRaccoon', src: 'casual/enemies/raccoon.png' },
    { id: 'frog', name: '개구리음유시인', hp: 42, speed: 48, gold: 8, dmg: 1, size: 44, move: 'ground', sprite: 'cFrog', src: 'casual/enemies/frog.png' },
    { id: 'turtle', name: '거북전차', hp: 85, speed: 32, gold: 12, dmg: 2, size: 50, move: 'ground', sprite: 'cTurtle', src: 'casual/enemies/turtle.png' },
    { id: 'squirrel', name: '도토리다람쥐', hp: 30, speed: 76, gold: 8, dmg: 1, size: 42, move: 'ground', sprite: 'cSquirrel', src: 'casual/enemies/squirrel.png' },
    { id: 'hedgehog', name: '고슴도치창병', hp: 40, speed: 46, gold: 8, dmg: 1, size: 42, move: 'ground', sprite: 'cHedgehog', src: 'casual/enemies/hedgehog.png' },
    { id: 'duck', name: '오리기사', hp: 44, speed: 58, gold: 8, dmg: 1, size: 46, move: 'ground', sprite: 'cDuck', src: 'casual/enemies/duck.png' },
    { id: 'panda', name: '팬더수도승', hp: 72, speed: 36, gold: 11, dmg: 2, size: 50, move: 'ground', sprite: 'cPanda', src: 'casual/enemies/panda.png' },
    { id: 'koala', name: '코알라우산', hp: 38, speed: 42, gold: 7, dmg: 1, size: 44, move: 'ground', sprite: 'cKoala', src: 'casual/enemies/koala.png' },
    { id: 'catsamurai', name: '고양이무사', hp: 48, speed: 68, gold: 10, dmg: 1, size: 46, move: 'ground', sprite: 'cCatsamurai', src: 'casual/enemies/catsamurai.png' },
    { id: 'goat', name: '염소등반가', hp: 55, speed: 50, gold: 9, dmg: 1, size: 48, move: 'ground', sprite: 'cGoat', src: 'casual/enemies/goat.png' },
    { id: 'otter', name: '수달창병', hp: 36, speed: 64, gold: 8, dmg: 1, size: 42, move: 'ground', sprite: 'cOtter', src: 'casual/enemies/otter.png' },
    { id: 'tanuki', name: '너구리요술사', hp: 42, speed: 52, gold: 9, dmg: 1, size: 46, move: 'ground', sprite: 'cTanuki', src: 'casual/enemies/tanuki.png' },
    { id: 'wolf', name: '늑대정찰', hp: 44, speed: 72, gold: 10, dmg: 1, size: 46, move: 'ground', sprite: 'cWolf', src: 'casual/enemies/wolf.png' },
    { id: 'boar', name: '멧돼지기사', hp: 78, speed: 40, gold: 12, dmg: 2, size: 50, move: 'ground', sprite: 'cBoar', src: 'casual/enemies/boar.png' },
    { id: 'mouse', name: '생쥐마법사', hp: 28, speed: 66, gold: 8, dmg: 1, size: 40, move: 'ground', sprite: 'cMouse', src: 'casual/enemies/mouse.png' },
    { id: 'chameleon', name: '카멜레온화가', hp: 40, speed: 54, gold: 9, dmg: 1, size: 44, move: 'ground', sprite: 'cChameleon', src: 'casual/enemies/chameleon.png' },
    { id: 'seahorse', name: '해마기사', hp: 36, speed: 58, gold: 8, dmg: 1, size: 44, move: 'ground', sprite: 'cSeahorse', src: 'casual/enemies/seahorse.png' },
    { id: 'alpaca', name: '알파카짐꾼', hp: 50, speed: 46, gold: 9, dmg: 1, size: 48, move: 'ground', sprite: 'cAlpaca', src: 'casual/enemies/alpaca.png' },
    { id: 'beaver', name: '비버목수', hp: 52, speed: 44, gold: 9, dmg: 1, size: 46, move: 'ground', sprite: 'cBeaver', src: 'casual/enemies/beaver.png' },
    { id: 'snake', name: '뱀닌자', hp: 34, speed: 82, gold: 10, dmg: 1, size: 42, move: 'ground', sprite: 'cSnake', src: 'casual/enemies/snake.png' },
    { id: 'porcupine', name: '호저방패', hp: 70, speed: 38, gold: 11, dmg: 2, size: 48, move: 'ground', sprite: 'cPorcupine', src: 'casual/enemies/porcupine.png' },
    { id: 'kiwi', name: '키위기사', hp: 40, speed: 50, gold: 8, dmg: 1, size: 44, move: 'ground', sprite: 'cKiwi', src: 'casual/enemies/kiwi.png' },
    { id: 'rhino', name: '아기코뿔소', hp: 88, speed: 34, gold: 13, dmg: 2, size: 52, move: 'ground', sprite: 'cRhino', src: 'casual/enemies/rhino.png' },
    { id: 'hippo', name: '하마선원', hp: 80, speed: 36, gold: 12, dmg: 2, size: 52, move: 'ground', sprite: 'cHippo', src: 'casual/enemies/hippo.png' },
    { id: 'capybara', name: '카피바라온천', hp: 60, speed: 40, gold: 10, dmg: 1, size: 50, move: 'ground', sprite: 'cCapybara', src: 'casual/enemies/capybara.png' },
    { id: 'axolotl', name: '아홀로틀마법', hp: 34, speed: 52, gold: 9, dmg: 1, size: 44, move: 'ground', sprite: 'cAxolotl', src: 'casual/enemies/axolotl.png' },
    { id: 'meerkat', name: '미어캣파수', hp: 32, speed: 70, gold: 8, dmg: 1, size: 42, move: 'ground', sprite: 'cMeerkat', src: 'casual/enemies/meerkat.png' },
    { id: 'lemur', name: '여우원숭이', hp: 38, speed: 68, gold: 9, dmg: 1, size: 44, move: 'ground', sprite: 'cLemur', src: 'casual/enemies/lemur.png' },
    { id: 'sloth', name: '나무늘보', hp: 55, speed: 28, gold: 8, dmg: 1, size: 48, move: 'ground', sprite: 'cSloth', src: 'casual/enemies/sloth.png' },
    { id: 'quokka', name: '쿼카꽃관', hp: 36, speed: 56, gold: 8, dmg: 1, size: 42, move: 'ground', sprite: 'cQuokka', src: 'casual/enemies/quokka.png' },
    { id: 'bison', name: '들소전사', hp: 90, speed: 36, gold: 13, dmg: 2, size: 54, move: 'ground', sprite: 'cBison', src: 'casual/enemies/bison.png' },
    { id: 'walrus', name: '바다코끼리', hp: 84, speed: 32, gold: 12, dmg: 2, size: 52, move: 'ground', sprite: 'cWalrus', src: 'casual/enemies/walrus.png' },
    { id: 'platypus', name: '오리너구리탐정', hp: 42, speed: 50, gold: 9, dmg: 1, size: 44, move: 'ground', sprite: 'cPlatypus', src: 'casual/enemies/platypus.png' },
    { id: 'hamster', name: '햄스터짐꾼', hp: 30, speed: 62, gold: 7, dmg: 1, size: 40, move: 'ground', sprite: 'cHamster', src: 'casual/enemies/hamster.png' },
    { id: 'skunk', name: '스컹크연금', hp: 38, speed: 54, gold: 9, dmg: 1, size: 44, move: 'ground', sprite: 'cSkunk', src: 'casual/enemies/skunk.png' },
    { id: 'weasel', name: '족제비도둑', hp: 32, speed: 80, gold: 9, dmg: 1, size: 40, move: 'ground', sprite: 'cWeasel', src: 'casual/enemies/weasel.png' },
    { id: 'camel', name: '낙타짐꾼', hp: 70, speed: 42, gold: 11, dmg: 2, size: 52, move: 'ground', sprite: 'cCamel', src: 'casual/enemies/camel.png' },
    { id: 'zebra', name: '얼룩말기사', hp: 48, speed: 68, gold: 10, dmg: 1, size: 48, move: 'ground', sprite: 'cZebra', src: 'casual/enemies/zebra.png' },
    { id: 'giraffe', name: '기린파수', hp: 60, speed: 46, gold: 11, dmg: 1, size: 54, move: 'ground', sprite: 'cGiraffe', src: 'casual/enemies/giraffe.png' },
    { id: 'crocodile', name: '악어선원', hp: 82, speed: 36, gold: 12, dmg: 2, size: 52, move: 'ground', sprite: 'cCrocodile', src: 'casual/enemies/crocodile.png' },
    { id: 'lynx', name: '스라소니궁수', hp: 44, speed: 72, gold: 10, dmg: 1, size: 46, move: 'ground', sprite: 'cLynx', src: 'casual/enemies/lynx.png' },
    { id: 'tapir', name: '맥우산', hp: 58, speed: 40, gold: 10, dmg: 1, size: 50, move: 'ground', sprite: 'cTapir', src: 'casual/enemies/tapir.png' },
    { id: 'elephant', name: '아기코끼리', hp: 95, speed: 32, gold: 14, dmg: 2, size: 56, move: 'ground', sprite: 'cElephant', src: 'casual/enemies/elephant.png' },
    { id: 'tiger', name: '호랑이새끼', hp: 52, speed: 74, gold: 12, dmg: 2, size: 48, move: 'ground', sprite: 'cTiger', src: 'casual/enemies/tiger.png' },
    { id: 'deer', name: '사슴정찰', hp: 40, speed: 70, gold: 9, dmg: 1, size: 46, move: 'ground', sprite: 'cDeer', src: 'casual/enemies/deer.png' },
    { id: 'llama', name: '라마짐꾼', hp: 54, speed: 48, gold: 10, dmg: 1, size: 50, move: 'ground', sprite: 'cLlama', src: 'casual/enemies/llama.png' },
    { id: 'monkey', name: '원숭이창병', hp: 36, speed: 76, gold: 9, dmg: 1, size: 42, move: 'ground', sprite: 'cMonkey', src: 'casual/enemies/monkey.png' },
    { id: 'yak', name: '야크전사', hp: 88, speed: 34, gold: 13, dmg: 2, size: 54, move: 'ground', sprite: 'cYak', src: 'casual/enemies/yak.png' },
    { id: 'bee', name: '꿀벌창병', hp: 22, speed: 88, gold: 8, dmg: 1, size: 42, move: 'air', sprite: 'cBee', src: 'casual/enemies/bee.png' },
    { id: 'balloon', name: '풍선임프', hp: 30, speed: 64, gold: 9, dmg: 1, size: 50, move: 'air', sprite: 'cBalloon', src: 'casual/enemies/balloon.png' },
    { id: 'bat', name: '가방박쥐', hp: 26, speed: 96, gold: 9, dmg: 1, size: 40, move: 'air', sprite: 'cBat', src: 'casual/enemies/bat.png' },
    { id: 'owl', name: '부엉이법사', hp: 34, speed: 72, gold: 10, dmg: 1, size: 48, move: 'air', sprite: 'cOwl', src: 'casual/enemies/owl.png' },
    { id: 'parrot', name: '연연앵무', hp: 28, speed: 84, gold: 9, dmg: 1, size: 46, move: 'air', sprite: 'cParrot', src: 'casual/enemies/parrot.png' },
    { id: 'dragonfly', name: '잠자리기사', hp: 24, speed: 100, gold: 10, dmg: 1, size: 42, move: 'air', sprite: 'cDragonfly', src: 'casual/enemies/dragonfly.png' },
    { id: 'cloudsheep', name: '구름양', hp: 40, speed: 60, gold: 11, dmg: 1, size: 50, move: 'air', sprite: 'cCloudsheep', src: 'casual/enemies/cloudsheep.png' },
    { id: 'humming', name: '벌새창기', hp: 20, speed: 110, gold: 10, dmg: 1, size: 38, move: 'air', sprite: 'cHumming', src: 'casual/enemies/humming.png' },
    { id: 'ladybug', name: '무당벌레방패', hp: 36, speed: 68, gold: 9, dmg: 1, size: 42, move: 'air', sprite: 'cLadybug', src: 'casual/enemies/ladybug.png' },
    { id: 'fairy', name: '민들레요정', hp: 22, speed: 90, gold: 11, dmg: 1, size: 42, move: 'air', sprite: 'cFairy', src: 'casual/enemies/fairy.png' },
    { id: 'crane', name: '종이학닌자', hp: 26, speed: 98, gold: 10, dmg: 1, size: 44, move: 'air', sprite: 'cCrane', src: 'casual/enemies/crane.png' },
    { id: 'pigeon', name: '비둘기우편', hp: 24, speed: 92, gold: 9, dmg: 1, size: 42, move: 'air', sprite: 'cPigeon', src: 'casual/enemies/pigeon.png' },
    { id: 'moth', name: '나방정찰', hp: 22, speed: 86, gold: 9, dmg: 1, size: 42, move: 'air', sprite: 'cMoth', src: 'casual/enemies/moth.png' },
    { id: 'firefly', name: '반딧불이', hp: 18, speed: 80, gold: 8, dmg: 1, size: 40, move: 'air', sprite: 'cFirefly', src: 'casual/enemies/firefly.png' },
    { id: 'pelican', name: '펠리컨우편', hp: 32, speed: 78, gold: 10, dmg: 1, size: 48, move: 'air', sprite: 'cPelican', src: 'casual/enemies/pelican.png' },
    { id: 'butterfly', name: '나비창기', hp: 16, speed: 96, gold: 8, dmg: 1, size: 40, move: 'air', sprite: 'cButterfly', src: 'casual/enemies/butterfly.png' },
    { id: 'jellyfish', name: '해파리종', hp: 28, speed: 62, gold: 9, dmg: 1, size: 44, move: 'air', sprite: 'cJellyfish', src: 'casual/enemies/jellyfish.png' },
    { id: 'toucan', name: '투칸해적', hp: 30, speed: 88, gold: 10, dmg: 1, size: 46, move: 'air', sprite: 'cToucan', src: 'casual/enemies/toucan.png' },
    { id: 'flamingo', name: '플라밍고무용', hp: 28, speed: 74, gold: 10, dmg: 1, size: 48, move: 'air', sprite: 'cFlamingo', src: 'casual/enemies/flamingo.png' },
    { id: 'eagle', name: '독수정찰', hp: 36, speed: 100, gold: 12, dmg: 1, size: 48, move: 'air', sprite: 'cEagle', src: 'casual/enemies/eagle.png' },
    { id: 'dragoncub', name: '아기용', hp: 48, speed: 70, gold: 14, dmg: 2, size: 50, move: 'air', sprite: 'cDragoncub', src: 'casual/enemies/dragoncub.png' },
    { id: 'squid', name: '오징어선원', hp: 34, speed: 66, gold: 10, dmg: 1, size: 46, move: 'air', sprite: 'cSquid', src: 'casual/enemies/squid.png' },
    { id: 'swan', name: '백조기사', hp: 40, speed: 72, gold: 11, dmg: 1, size: 50, move: 'air', sprite: 'cSwan', src: 'casual/enemies/swan.png' },
    { id: 'pegasus', name: '아기페가수스', hp: 44, speed: 88, gold: 13, dmg: 2, size: 50, move: 'air', sprite: 'cPegasus', src: 'casual/enemies/pegasus.png' },
    { id: 'puffin', name: '퍼핀해적', hp: 28, speed: 84, gold: 10, dmg: 1, size: 44, move: 'air', sprite: 'cPuffin', src: 'casual/enemies/puffin.png' },
    { id: 'kite', name: '연새', hp: 20, speed: 104, gold: 9, dmg: 1, size: 42, move: 'air', sprite: 'cKite', src: 'casual/enemies/kite.png' },
    { id: 'phoenix', name: '아기불사조', hp: 46, speed: 78, gold: 14, dmg: 2, size: 48, move: 'air', sprite: 'cPhoenix', src: 'casual/enemies/phoenix.png' },
    { id: 'griffin', name: '아기그리핀', hp: 50, speed: 82, gold: 14, dmg: 2, size: 50, move: 'air', sprite: 'cGriffin', src: 'casual/enemies/griffin.png' },
    { id: 'hornet', name: '말벌정찰', hp: 22, speed: 108, gold: 10, dmg: 1, size: 40, move: 'air', sprite: 'cHornet', src: 'casual/enemies/hornet.png' },
    { id: 'firebird', name: '불새리본', hp: 34, speed: 90, gold: 12, dmg: 1, size: 46, move: 'air', sprite: 'cFirebird', src: 'casual/enemies/firebird.png' },
    { id: 'seagull', name: '갈매기해적', hp: 26, speed: 88, gold: 10, dmg: 1, size: 44, move: 'air', sprite: 'cSeagull', src: 'casual/enemies/seagull.png' },
    { id: 'wyvern', name: '아기와이번', hp: 52, speed: 76, gold: 14, dmg: 2, size: 50, move: 'air', sprite: 'cWyvern', src: 'casual/enemies/wyvern.png' },
    { id: 'sparrow', name: '참새우편', hp: 18, speed: 106, gold: 8, dmg: 1, size: 38, move: 'air', sprite: 'cSparrow', src: 'casual/enemies/sparrow.png' },
    { id: 'unicorn', name: '아기유니콘', hp: 48, speed: 84, gold: 14, dmg: 2, size: 50, move: 'air', sprite: 'cUnicorn', src: 'casual/enemies/unicorn.png' },
    { id: 'mole', name: '두더지광부', hp: 44, speed: 54, gold: 8, dmg: 1, size: 44, move: 'burrow', sprite: 'cMole', src: 'casual/enemies/mole.png' },
    { id: 'worm', name: '모래벌레', hp: 55, speed: 40, gold: 10, dmg: 2, size: 50, move: 'burrow', sprite: 'cWorm', src: 'casual/enemies/worm.png' },
    { id: 'arma', name: '아르마딜로', hp: 70, speed: 38, gold: 11, dmg: 2, size: 48, move: 'burrow', sprite: 'cArma', src: 'casual/enemies/arma.png' },
    { id: 'beetle', name: '장수풍뎅이', hp: 60, speed: 42, gold: 10, dmg: 2, size: 46, move: 'burrow', sprite: 'cBeetle', src: 'casual/enemies/beetle.png' },
    { id: 'crab', name: '소라게', hp: 50, speed: 46, gold: 9, dmg: 1, size: 44, move: 'burrow', sprite: 'cCrab', src: 'casual/enemies/crab.png' },
    { id: 'prairie', name: '프레리독', hp: 48, speed: 50, gold: 9, dmg: 1, size: 44, move: 'burrow', sprite: 'cPrairie', src: 'casual/enemies/prairie.png' },
    { id: 'rabbit', name: '구멍토끼', hp: 34, speed: 70, gold: 9, dmg: 1, size: 42, move: 'burrow', sprite: 'cRabbit', src: 'casual/enemies/rabbit.png' },
    { id: 'badger', name: '오소리광부', hp: 58, speed: 44, gold: 10, dmg: 2, size: 46, move: 'burrow', sprite: 'cBadger', src: 'casual/enemies/badger.png' },
    { id: 'chipmunk', name: '칩멍크', hp: 32, speed: 74, gold: 8, dmg: 1, size: 40, move: 'burrow', sprite: 'cChipmunk', src: 'casual/enemies/chipmunk.png' },
    { id: 'wormknight', name: '지렁이기사', hp: 50, speed: 40, gold: 9, dmg: 2, size: 44, move: 'burrow', sprite: 'cWormknight', src: 'casual/enemies/wormknight.png' },
    { id: 'vole', name: '들쥐등불', hp: 34, speed: 58, gold: 8, dmg: 1, size: 40, move: 'burrow', sprite: 'cVole', src: 'casual/enemies/vole.png' },
    { id: 'pangolin', name: '천산갑', hp: 80, speed: 34, gold: 12, dmg: 2, size: 50, move: 'burrow', sprite: 'cPangolin', src: 'casual/enemies/pangolin.png' },
    { id: 'ant', name: '개미병정', hp: 30, speed: 62, gold: 7, dmg: 1, size: 38, move: 'burrow', sprite: 'cAnt', src: 'casual/enemies/ant.png' },
    { id: 'gecko', name: '도마뱀헬멧', hp: 36, speed: 60, gold: 8, dmg: 1, size: 40, move: 'burrow', sprite: 'cGecko', src: 'casual/enemies/gecko.png' },
    { id: 'wombat', name: '웜뱃광부', hp: 64, speed: 40, gold: 11, dmg: 2, size: 48, move: 'burrow', sprite: 'cWombat', src: 'casual/enemies/wombat.png' },
    { id: 'ferret', name: '페럿도둑', hp: 32, speed: 78, gold: 9, dmg: 1, size: 40, move: 'burrow', sprite: 'cFerret', src: 'casual/enemies/ferret.png' },
    { id: 'centipede', name: '지네기사', hp: 58, speed: 48, gold: 11, dmg: 2, size: 46, move: 'burrow', sprite: 'cCentipede', src: 'casual/enemies/centipede.png' },
    { id: 'shrew', name: '땃쥐등불', hp: 28, speed: 76, gold: 8, dmg: 1, size: 38, move: 'burrow', sprite: 'cShrew', src: 'casual/enemies/shrew.png' },
    { id: 'termite', name: '흰개미병정', hp: 26, speed: 64, gold: 7, dmg: 1, size: 36, move: 'burrow', sprite: 'cTermite', src: 'casual/enemies/termite.png' },
    { id: 'molecricket', name: '땅강아지', hp: 40, speed: 52, gold: 9, dmg: 1, size: 42, move: 'burrow', sprite: 'cMolecricket', src: 'casual/enemies/molecricket.png' },
    { id: 'gopher', name: '고퍼광부', hp: 46, speed: 54, gold: 9, dmg: 1, size: 42, move: 'burrow', sprite: 'cGopher', src: 'casual/enemies/gopher.png' },
    { id: 'cicada', name: '매미약충', hp: 34, speed: 50, gold: 8, dmg: 1, size: 40, move: 'burrow', sprite: 'cCicada', src: 'casual/enemies/cicada.png' },
    { id: 'sandfish', name: '모래고기', hp: 38, speed: 58, gold: 9, dmg: 1, size: 42, move: 'burrow', sprite: 'cSandfish', src: 'casual/enemies/sandfish.png' },
    { id: 'spider', name: '함정거미', hp: 44, speed: 48, gold: 10, dmg: 1, size: 44, move: 'burrow', sprite: 'cSpider', src: 'casual/enemies/spider.png' },
    { id: 'lioncub', name: '아기사자', hp: 48, speed: 72, gold: 11, dmg: 1, size: 46, move: 'ground', sprite: 'cLioncub', src: 'casual/enemies/lioncub.png' },
    { id: 'kangaroo', name: '아기캥거루', hp: 52, speed: 64, gold: 11, dmg: 1, size: 48, move: 'ground', sprite: 'cKangaroo', src: 'casual/enemies/kangaroo.png' },
    { id: 'ostrich', name: '타조병정', hp: 46, speed: 78, gold: 10, dmg: 1, size: 50, move: 'ground', sprite: 'cOstrich', src: 'casual/enemies/ostrich.png' },
    { id: 'dodo', name: '도도탐험가', hp: 70, speed: 34, gold: 12, dmg: 2, size: 50, move: 'ground', sprite: 'cDodo', src: 'casual/enemies/dodo.png' },
    { id: 'peacock', name: '공작기사', hp: 44, speed: 56, gold: 11, dmg: 1, size: 50, move: 'ground', sprite: 'cPeacock', src: 'casual/enemies/peacock.png' },
    { id: 'cheetah', name: '치타정찰', hp: 38, speed: 92, gold: 12, dmg: 1, size: 46, move: 'ground', sprite: 'cCheetah', src: 'casual/enemies/cheetah.png' },
    { id: 'raven', name: '까마귀정찰', hp: 24, speed: 100, gold: 10, dmg: 1, size: 42, move: 'air', sprite: 'cRaven', src: 'casual/enemies/raven.png' },
    { id: 'hawk', name: '매정찰', hp: 32, speed: 104, gold: 11, dmg: 1, size: 46, move: 'air', sprite: 'cHawk', src: 'casual/enemies/hawk.png' },
    { id: 'macaw', name: '마카우전령', hp: 28, speed: 90, gold: 10, dmg: 1, size: 46, move: 'air', sprite: 'cMacaw', src: 'casual/enemies/macaw.png' },
    { id: 'locust', name: '메뚜기정찰', hp: 22, speed: 108, gold: 10, dmg: 1, size: 40, move: 'air', sprite: 'cLocust', src: 'casual/enemies/locust.png' },
    { id: 'scorpion', name: '전갈무사', hp: 58, speed: 44, gold: 11, dmg: 2, size: 46, move: 'burrow', sprite: 'cScorpion', src: 'casual/enemies/scorpion.png' },
    { id: 'pillbug', name: '공벌레방패', hp: 72, speed: 32, gold: 12, dmg: 2, size: 48, move: 'burrow', sprite: 'cPillbug', src: 'casual/enemies/pillbug.png' },
  ];
  const bossBases = [
    { id: 'kingSlime', name: '슬라임왕', hp: 720, speed: 28, gold: 90, dmg: 4, size: 86, move: 'ground', sprite: 'cKingSlime', src: 'casual/bosses/king-slime.png' },
    { id: 'diceDragon', name: '주사위용', hp: 980, speed: 30, gold: 120, dmg: 5, size: 92, move: 'air', sprite: 'cDiceDragon', src: 'casual/bosses/dice-dragon.png' },
    { id: 'ogreChef', name: '주사위요리사', hp: 1100, speed: 24, gold: 130, dmg: 5, size: 90, move: 'ground', sprite: 'cOgreChef', src: 'casual/bosses/ogre-chef.png' },
    { id: 'pumpkinKing', name: '호박왕', hp: 880, speed: 26, gold: 110, dmg: 4, size: 88, move: 'ground', sprite: 'cPumpkinKing', src: 'casual/bosses/pumpkin-king.png' },
    { id: 'yeti', name: '주사위예티', hp: 1050, speed: 22, gold: 125, dmg: 5, size: 92, move: 'ground', sprite: 'cYeti', src: 'casual/bosses/yeti.png' },
    { id: 'candyGolem', name: '사탕골렘', hp: 1200, speed: 20, gold: 140, dmg: 5, size: 94, move: 'ground', sprite: 'cCandyGolem', src: 'casual/bosses/candy-golem.png' },
    { id: 'kraken', name: '해적크라켄', hp: 960, speed: 32, gold: 130, dmg: 5, size: 90, move: 'air', sprite: 'cKraken', src: 'casual/bosses/kraken.png' },
    { id: 'clockOwl', name: '태엽올빼미', hp: 1080, speed: 26, gold: 135, dmg: 5, size: 90, move: 'air', sprite: 'cClockOwl', src: 'casual/bosses/clock-owl.png' },
    { id: 'coralQueen', name: '산호여왕', hp: 1020, speed: 28, gold: 128, dmg: 5, size: 88, move: 'ground', sprite: 'cCoralQueen', src: 'casual/bosses/coral-queen.png' },
    { id: 'ghostKing', name: '유령왕', hp: 940, speed: 34, gold: 122, dmg: 5, size: 88, move: 'air', sprite: 'cGhostKing', src: 'casual/bosses/ghost-king.png' },
    { id: 'honeyBear', name: '꿀곰대왕', hp: 1250, speed: 22, gold: 145, dmg: 5, size: 94, move: 'ground', sprite: 'cHoneyBear', src: 'casual/bosses/honey-bear.png' },
    { id: 'lionMaster', name: '서커스사자', hp: 1120, speed: 30, gold: 138, dmg: 5, size: 90, move: 'ground', sprite: 'cLionMaster', src: 'casual/bosses/lion-master.png' },
    { id: 'mapleTreant', name: '단풍정령', hp: 1180, speed: 24, gold: 140, dmg: 5, size: 94, move: 'ground', sprite: 'cMapleTreant', src: 'casual/bosses/maple-treant.png' },
    { id: 'auroraMoose', name: '오로라무스', hp: 1080, speed: 28, gold: 136, dmg: 5, size: 92, move: 'ground', sprite: 'cAuroraMoose', src: 'casual/bosses/aurora-moose.png' },
    { id: 'gorillaKing', name: '정글고릴라왕', hp: 1300, speed: 22, gold: 150, dmg: 6, size: 96, move: 'ground', sprite: 'cGorillaKing', src: 'casual/bosses/gorilla-king.png' },
    { id: 'peacockKing', name: '공작왕', hp: 1150, speed: 28, gold: 142, dmg: 5, size: 90, move: 'ground', sprite: 'cPeacockKing', src: 'casual/bosses/peacock-king.png' },
    { id: 'skiYeti', name: '스키예티셰프', hp: 1220, speed: 24, gold: 144, dmg: 5, size: 92, move: 'ground', sprite: 'cSkiYeti', src: 'casual/bosses/ski-yeti.png' },
    { id: 'astroSlime', name: '우주슬라임', hp: 1000, speed: 34, gold: 138, dmg: 5, size: 88, move: 'air', sprite: 'cAstroSlime', src: 'casual/bosses/astro-slime.png' },
    { id: 'harborOcto', name: '등대문어', hp: 1180, speed: 26, gold: 140, dmg: 5, size: 92, move: 'air', sprite: 'cHarborOcto', src: 'casual/bosses/harbor-octo.png' },
    { id: 'wolfKing', name: '늑대왕', hp: 1160, speed: 30, gold: 142, dmg: 5, size: 90, move: 'ground', sprite: 'cWolfKing', src: 'casual/bosses/wolf-king.png' },
    { id: 'boarWarlord', name: '멧돼지장군', hp: 1340, speed: 22, gold: 152, dmg: 6, size: 96, move: 'ground', sprite: 'cBoarWarlord', src: 'casual/bosses/boar-warlord.png' },
    { id: 'mothQueen', name: '나방여왕', hp: 980, speed: 32, gold: 136, dmg: 5, size: 88, move: 'air', sprite: 'cMothQueen', src: 'casual/bosses/moth-queen.png' },
    { id: 'pangolinTank', name: '천산갑전차', hp: 1400, speed: 20, gold: 155, dmg: 6, size: 94, move: 'burrow', sprite: 'cPangolinTank', src: 'casual/bosses/pangolin-tank.png' },
    { id: 'alpacaKing', name: '알파카왕', hp: 1100, speed: 26, gold: 140, dmg: 5, size: 92, move: 'ground', sprite: 'cAlpacaKing', src: 'casual/bosses/alpaca-king.png' },
    { id: 'mouseKing', name: '생쥐마왕', hp: 920, speed: 34, gold: 134, dmg: 5, size: 86, move: 'ground', sprite: 'cMouseKing', src: 'casual/bosses/mouse-king.png' },
    { id: 'antQueen', name: '개미여왕', hp: 1080, speed: 24, gold: 138, dmg: 5, size: 90, move: 'burrow', sprite: 'cAntQueen', src: 'casual/bosses/ant-queen.png' },
    { id: 'chameleonHydra', name: '카멜레온히드라', hp: 1260, speed: 26, gold: 148, dmg: 6, size: 94, move: 'ground', sprite: 'cChameleonHydra', src: 'casual/bosses/chameleon-hydra.png' },
    { id: 'beaverLord', name: '비버영주', hp: 1140, speed: 24, gold: 140, dmg: 5, size: 90, move: 'ground', sprite: 'cBeaverLord', src: 'casual/bosses/beaver-lord.png' },
    { id: 'jellyQueen', name: '해파리여왕', hp: 960, speed: 30, gold: 134, dmg: 5, size: 88, move: 'air', sprite: 'cJellyQueen', src: 'casual/bosses/jelly-queen.png' },
    { id: 'toucanCaptain', name: '투칸선장', hp: 1020, speed: 32, gold: 138, dmg: 5, size: 90, move: 'air', sprite: 'cToucanCaptain', src: 'casual/bosses/toucan-captain.png' },
    { id: 'nagaKing', name: '나가왕', hp: 1180, speed: 28, gold: 144, dmg: 5, size: 92, move: 'ground', sprite: 'cNagaKing', src: 'casual/bosses/naga-king.png' },
    { id: 'hippoAdmiral', name: '하마제독', hp: 1280, speed: 22, gold: 148, dmg: 6, size: 96, move: 'ground', sprite: 'cHippoAdmiral', src: 'casual/bosses/hippo-admiral.png' },
    { id: 'porcupineTank', name: '호저전차', hp: 1360, speed: 20, gold: 152, dmg: 6, size: 94, move: 'ground', sprite: 'cPorcupineTank', src: 'casual/bosses/porcupine-tank.png' },
    { id: 'kiwiPaladin', name: '키위성기사', hp: 1080, speed: 26, gold: 140, dmg: 5, size: 90, move: 'ground', sprite: 'cKiwiPaladin', src: 'casual/bosses/kiwi-paladin.png' },
    { id: 'rhinoChief', name: '코뿔소족장', hp: 1420, speed: 20, gold: 158, dmg: 6, size: 98, move: 'ground', sprite: 'cRhinoChief', src: 'casual/bosses/rhino-chief.png' },
    { id: 'capybaraKing', name: '카피바라왕', hp: 1200, speed: 24, gold: 144, dmg: 5, size: 92, move: 'ground', sprite: 'cCapybaraKing', src: 'casual/bosses/capybara-king.png' },
    { id: 'axolotlSage', name: '아홀로틀현자', hp: 980, speed: 28, gold: 136, dmg: 5, size: 88, move: 'ground', sprite: 'cAxolotlSage', src: 'casual/bosses/axolotl-sage.png' },
    { id: 'flamingoQueen', name: '플라밍고여왕', hp: 1040, speed: 30, gold: 138, dmg: 5, size: 90, move: 'air', sprite: 'cFlamingoQueen', src: 'casual/bosses/flamingo-queen.png' },
    { id: 'eagleEmperor', name: '독수정제', hp: 1120, speed: 32, gold: 146, dmg: 5, size: 92, move: 'air', sprite: 'cEagleEmperor', src: 'casual/bosses/eagle-emperor.png' },
    { id: 'slothMonk', name: '나무늘보승', hp: 1300, speed: 18, gold: 148, dmg: 5, size: 94, move: 'ground', sprite: 'cSlothMonk', src: 'casual/bosses/sloth-monk.png' },
    { id: 'dragonKing', name: '아기용왕', hp: 1380, speed: 26, gold: 160, dmg: 6, size: 96, move: 'air', sprite: 'cDragonKing', src: 'casual/bosses/dragon-king.png' },
    { id: 'lemurKing', name: '여우원숭이왕', hp: 1080, speed: 28, gold: 140, dmg: 5, size: 90, move: 'ground', sprite: 'cLemurKing', src: 'casual/bosses/lemur-king.png' },
    { id: 'squidAdmiral', name: '오징어제독', hp: 1160, speed: 26, gold: 142, dmg: 5, size: 92, move: 'air', sprite: 'cSquidAdmiral', src: 'casual/bosses/squid-admiral.png' },
    { id: 'bisonChief', name: '들소족장', hp: 1440, speed: 20, gold: 158, dmg: 6, size: 98, move: 'ground', sprite: 'cBisonChief', src: 'casual/bosses/bison-chief.png' },
    { id: 'walrusAdmiral', name: '바다코끼리제독', hp: 1320, speed: 22, gold: 150, dmg: 6, size: 96, move: 'ground', sprite: 'cWalrusAdmiral', src: 'casual/bosses/walrus-admiral.png' },
    { id: 'platypusChief', name: '오리너구리반장', hp: 1060, speed: 28, gold: 138, dmg: 5, size: 88, move: 'ground', sprite: 'cPlatypusChief', src: 'casual/bosses/platypus-chief.png' },
    { id: 'hamsterKing', name: '햄스터왕', hp: 940, speed: 30, gold: 132, dmg: 5, size: 86, move: 'ground', sprite: 'cHamsterKing', src: 'casual/bosses/hamster-king.png' },
    { id: 'swanQueen', name: '백조여왕', hp: 1100, speed: 28, gold: 142, dmg: 5, size: 92, move: 'air', sprite: 'cSwanQueen', src: 'casual/bosses/swan-queen.png' },
    { id: 'pegasusKing', name: '페가수스왕', hp: 1240, speed: 32, gold: 152, dmg: 6, size: 94, move: 'air', sprite: 'cPegasusKing', src: 'casual/bosses/pegasus-king.png' },
    { id: 'skunkMaster', name: '스컹크대현자', hp: 1080, speed: 26, gold: 140, dmg: 5, size: 90, move: 'ground', sprite: 'cSkunkMaster', src: 'casual/bosses/skunk-master.png' },
    { id: 'puffinCaptain', name: '퍼핀선장', hp: 1020, speed: 30, gold: 138, dmg: 5, size: 90, move: 'air', sprite: 'cPuffinCaptain', src: 'casual/bosses/puffin-captain.png' },
    { id: 'camelSultan', name: '낙타술탄', hp: 1260, speed: 24, gold: 146, dmg: 5, size: 94, move: 'ground', sprite: 'cCamelSultan', src: 'casual/bosses/camel-sultan.png' },
    { id: 'zebraKing', name: '얼룩말왕', hp: 1140, speed: 28, gold: 142, dmg: 5, size: 90, move: 'ground', sprite: 'cZebraKing', src: 'casual/bosses/zebra-king.png' },
    { id: 'giraffeKing', name: '기린왕', hp: 1180, speed: 26, gold: 144, dmg: 5, size: 96, move: 'ground', sprite: 'cGiraffeKing', src: 'casual/bosses/giraffe-king.png' },
    { id: 'crocAdmiral', name: '악어제독', hp: 1340, speed: 22, gold: 150, dmg: 6, size: 96, move: 'ground', sprite: 'cCrocAdmiral', src: 'casual/bosses/croc-admiral.png' },
    { id: 'lynxCaptain', name: '스라소니대장', hp: 1080, speed: 30, gold: 140, dmg: 5, size: 88, move: 'ground', sprite: 'cLynxCaptain', src: 'casual/bosses/lynx-captain.png' },
    { id: 'phoenixKing', name: '불사조왕', hp: 1280, speed: 30, gold: 156, dmg: 6, size: 94, move: 'air', sprite: 'cPhoenixKing', src: 'casual/bosses/phoenix-king.png' },
    { id: 'griffinEmperor', name: '그리핀황제', hp: 1360, speed: 28, gold: 158, dmg: 6, size: 96, move: 'air', sprite: 'cGriffinEmperor', src: 'casual/bosses/griffin-emperor.png' },
    { id: 'hornetQueen', name: '말벌여왕', hp: 980, speed: 34, gold: 138, dmg: 5, size: 88, move: 'air', sprite: 'cHornetQueen', src: 'casual/bosses/hornet-queen.png' },
    { id: 'elephantRaja', name: '코끼리라자', hp: 1500, speed: 18, gold: 162, dmg: 6, size: 100, move: 'ground', sprite: 'cElephantRaja', src: 'casual/bosses/elephant-raja.png' },
    { id: 'tigerRaja', name: '호랑이라자', hp: 1220, speed: 30, gold: 150, dmg: 6, size: 92, move: 'ground', sprite: 'cTigerRaja', src: 'casual/bosses/tiger-raja.png' },
    { id: 'stagKing', name: '사슴왕', hp: 1120, speed: 28, gold: 142, dmg: 5, size: 90, move: 'ground', sprite: 'cStagKing', src: 'casual/bosses/stag-king.png' },
    { id: 'llamaKing', name: '라마왕', hp: 1160, speed: 26, gold: 144, dmg: 5, size: 92, move: 'ground', sprite: 'cLlamaKing', src: 'casual/bosses/llama-king.png' },
    { id: 'monkeyKing', name: '원숭이왕', hp: 1080, speed: 32, gold: 146, dmg: 5, size: 88, move: 'ground', sprite: 'cMonkeyKing', src: 'casual/bosses/monkey-king.png' },
    { id: 'yakChief', name: '야크족장', hp: 1380, speed: 20, gold: 154, dmg: 6, size: 96, move: 'ground', sprite: 'cYakChief', src: 'casual/bosses/yak-chief.png' },
    { id: 'wyvernKing', name: '와이번왕', hp: 1320, speed: 28, gold: 158, dmg: 6, size: 94, move: 'air', sprite: 'cWyvernKing', src: 'casual/bosses/wyvern-king.png' },
    { id: 'unicornQueen', name: '유니콘여왕', hp: 1200, speed: 30, gold: 152, dmg: 5, size: 92, move: 'air', sprite: 'cUnicornQueen', src: 'casual/bosses/unicorn-queen.png' },
    { id: 'kangarooKing', name: '캥거루왕', hp: 1240, speed: 28, gold: 150, dmg: 6, size: 94, move: 'ground', sprite: 'cKangarooKing', src: 'casual/bosses/kangaroo-king.png' },
    { id: 'ostrichKing', name: '타조왕', hp: 1180, speed: 30, gold: 146, dmg: 5, size: 94, move: 'ground', sprite: 'cOstrichKing', src: 'casual/bosses/ostrich-king.png' },
    { id: 'dodoKing', name: '도도왕', hp: 1320, speed: 20, gold: 148, dmg: 5, size: 96, move: 'ground', sprite: 'cDodoKing', src: 'casual/bosses/dodo-king.png' },
    { id: 'ravenKing', name: '까마귀왕', hp: 1080, speed: 32, gold: 142, dmg: 5, size: 90, move: 'air', sprite: 'cRavenKing', src: 'casual/bosses/raven-king.png' },
    { id: 'hawkEmperor', name: '매황제', hp: 1220, speed: 32, gold: 154, dmg: 6, size: 92, move: 'air', sprite: 'cHawkEmperor', src: 'casual/bosses/hawk-emperor.png' },
    { id: 'macawCaptain', name: '마카우선장', hp: 1100, speed: 30, gold: 144, dmg: 5, size: 90, move: 'air', sprite: 'cMacawCaptain', src: 'casual/bosses/macaw-captain.png' },
    { id: 'locustQueen', name: '메뚜기여왕', hp: 1020, speed: 34, gold: 140, dmg: 5, size: 88, move: 'air', sprite: 'cLocustQueen', src: 'casual/bosses/locust-queen.png' },
    { id: 'scorpionKing', name: '전갈왕', hp: 1400, speed: 22, gold: 156, dmg: 6, size: 96, move: 'burrow', sprite: 'cScorpionKing', src: 'casual/bosses/scorpion-king.png' },
  ];
  const ADJ = ['꼬마','숲','사탕','해변','눈꽃','달빛','황금','그림자','불꽃','이슬','돌','바람','꿀','구름','별','호박','산호','이끼','진주','장난','민트','코코아','벚꽃','밤하늘','햇살'];
  const RANK = ['신병','정찰','순찰','특공','정예','대장','파수','약탈','유랑','친위'];
  const species = [];
  for (let i = 0; i < 500; i++) {
    const b = bases[i % bases.length];
    const name = ADJ[i % ADJ.length] + ' ' + b.name + ' ' + RANK[Math.floor(i / bases.length) % RANK.length];
    species.push({ id: i, name, base: b.id, hue: (i * 47) % 360, hpM: 1 + (i % 7) * 0.06, spM: 1 + (i % 5) * 0.04 });
  }
  const BOSS_TITLE = ['왕','대공','폭군','제왕','군주','대장','수호신','악당','전설','우두머리'];
  const bosses = [];
  for (let i = 0; i < 100; i++) {
    const b = bossBases[i % bossBases.length];
    bosses.push({
      id: i,
      name: ADJ[i % ADJ.length] + ' ' + b.name + ' ' + BOSS_TITLE[i % BOSS_TITLE.length],
      base: b.id,
      hue: (i * 33) % 360,
      hpM: 1 + i * 0.08,
    });
  }
  return { maps, towerSkins, bases, bossBases, species, bosses, mapCount: 50, stageCount: 100 };
})();
