// Generated by commerce/build.mjs; liveops-rules.js normalized SHA256 a3730e91b3ab5f8297fa8c827ec7c11768e57c49b626e6607cb396b494b469c9
const module = { exports: {} };
(function (root, factory) {
  'use strict';
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  if (root && typeof root === 'object') root.DKLIVEOPS = api;
})(typeof window !== 'undefined' ? window : null, function () {
  'use strict';
  const VERSION = 1, MAX_ATTENDANCE = 1000000000, RUN_HISTORY = 64;
  const PASS_ID = 'founders', PASS_TIERS = 20, XP_PER_TIER = 100, MAX_XP = PASS_TIERS * XP_PER_TIER;
  const ATTENDANCE_XP = 20, KST_OFFSET_MS = 9 * 60 * 60 * 1000;
  const ATTENDANCE = Object.freeze([[100,3],[120,3],[140,4],[160,4],[180,5],[200,5],[300,10]]
    .map(([gold,shards], i) => Object.freeze({ cycleDay: i + 1, gold, shards, xp: ATTENDANCE_XP })));
  const PASS = Object.freeze({ id: PASS_ID, name: '창립자 성장 패스', tiers: PASS_TIERS, xpPerTier: XP_PER_TIER,
    maxXp: MAX_XP, priceKRW: 2900, subscription: false, expiresAt: null,
    free: Object.freeze({ gold: 100, shards: 2 }), premium: Object.freeze({ gold: 0, shards: 10 }),
    skinTier: 10, skinId: 'royal' });
  const MODES = Object.freeze(['clear', 'build', 'extreme', 'multi', 'extremeMulti', 'duel', 'coop']);
  const integer = (n, min, max) => Number.isSafeInteger(n) && n >= min && n <= max;
  const object = x => !!x && typeof x === 'object' && !Array.isArray(x);
  const idValid = id => typeof id === 'string' && id.length > 0 && id.length <= 128 && !/[\u0000-\u001f\u007f]/.test(id);
  function dayValid(day) {
    if (typeof day !== 'string' || !/^[2-9]\d{3}-\d{2}-\d{2}$/.test(day)) return false;
    const date = new Date(day + 'T00:00:00.000Z');
    return Number.isFinite(date.getTime()) && date.toISOString().slice(0, 10) === day;
  }
  // Callers pass authoritative server time; guest mode necessarily uses the
  // device clock. The shared rule does not authenticate clocks or entitlements.
  function dayKey(now = Date.now()) {
    const ms = typeof now === 'number' ? now : now instanceof Date ? now.getTime()
      : typeof now === 'string' && /T.*(?:Z|[+-]\d{2}:\d{2})$/i.test(now) ? Date.parse(now) : NaN;
    if (!Number.isFinite(ms)) return null;
    const date = new Date(ms + KST_OFFSET_MS);
    if (!Number.isFinite(date.getTime())) return null;
    const day = date.toISOString().slice(0, 10);
    return dayValid(day) ? day : null;
  }
  function defaultState() {
    return { version: VERSION, attendance: { lastDay: '', total: 0 },
      pass: { id: PASS_ID, xp: 0, freeClaimed: [], premiumClaimed: [] }, xpRuns: [] };
  }
  const claimsValid = (list, unlocked) => Array.isArray(list) && list.length <= PASS_TIERS
    && list.every(tier => integer(tier, 1, unlocked)) && new Set(list).size === list.length;
  function stateValid(state) {
    return object(state) && state.version === VERSION && object(state.attendance)
      && integer(state.attendance.total, 0, MAX_ATTENDANCE)
      && (state.attendance.total === 0 ? state.attendance.lastDay === '' : dayValid(state.attendance.lastDay))
      && object(state.pass) && state.pass.id === PASS_ID && integer(state.pass.xp, 0, MAX_XP)
      && claimsValid(state.pass.freeClaimed, Math.floor(state.pass.xp / XP_PER_TIER))
      && claimsValid(state.pass.premiumClaimed, Math.floor(state.pass.xp / XP_PER_TIER))
      && Array.isArray(state.xpRuns) && state.xpRuns.length <= RUN_HISTORY && state.xpRuns.every(idValid)
      && new Set(state.xpRuns).size === state.xpRuns.length;
  }
  function sanitize(raw) {
    const state = defaultState();
    if (!object(raw) || raw.version !== VERSION) return state;
    const finiteInt = (n, max) => typeof n === 'number' && Number.isFinite(n) ? Math.max(0, Math.min(max, Math.floor(n))) : 0;
    if (object(raw.attendance)) {
      const total = finiteInt(raw.attendance.total, MAX_ATTENDANCE);
      if (total > 0 && dayValid(raw.attendance.lastDay)) state.attendance = { total, lastDay: raw.attendance.lastDay };
    }
    if (object(raw.pass) && raw.pass.id === PASS_ID) {
      state.pass.xp = finiteInt(raw.pass.xp, MAX_XP);
      const unlocked = Math.floor(state.pass.xp / XP_PER_TIER);
      for (const key of ['freeClaimed', 'premiumClaimed']) state.pass[key] = Array.from({ length: unlocked }, (_, i) => i + 1)
        .filter(tier => Array.isArray(raw.pass[key]) && raw.pass[key].includes(tier));
    }
    if (Array.isArray(raw.xpRuns)) state.xpRuns = [...new Set(raw.xpRuns.filter(idValid))].slice(0, RUN_HISTORY);
    return state;
  }
  const clone = state => ({ version: VERSION, attendance: { ...state.attendance },
    pass: { id: PASS_ID, xp: state.pass.xp, freeClaimed: state.pass.freeClaimed.slice(), premiumClaimed: state.pass.premiumClaimed.slice() }, xpRuns: state.xpRuns.slice() });
  const noReward = () => ({ gold: 0, shards: 0 });
  const rejected = reason => ({ ok: false, reason, reward: noReward() });
  function tierReward(tier, track) {
    if (!integer(tier, 1, PASS_TIERS) || !['free', 'premium'].includes(track)) return null;
    return { ...PASS[track], ...(track === 'premium' && tier === PASS.skinTier ? { skinId: PASS.skinId } : {}) };
  }
  function view(state, options = {}) {
    if (!stateValid(state) || !object(options)) return null;
    const { now = Date.now(), premium = false } = options;
    const today = dayKey(now); if (!today) return null;
    const cycleDay = state.attendance.total % ATTENDANCE.length + 1, unlocked = Math.floor(state.pass.xp / XP_PER_TIER);
    return { version: VERSION,
      attendance: { dayKey: today, lastDay: state.attendance.lastDay, total: state.attendance.total, cycleDay,
        canClaim: state.attendance.lastDay < today && state.attendance.total < MAX_ATTENDANCE,
        nextReward: { ...ATTENDANCE[cycleDay - 1] }, cycle: ATTENDANCE.map(row => ({ ...row })) },
      pass: { ...PASS, free: { ...PASS.free }, premium: { ...PASS.premium }, owned: premium === true, xp: state.pass.xp, unlocked,
        xpInTier: state.pass.xp === MAX_XP ? XP_PER_TIER : state.pass.xp % XP_PER_TIER,
        nextTierXp: state.pass.xp === MAX_XP ? null : (unlocked + 1) * XP_PER_TIER,
        tiers: Array.from({ length: PASS_TIERS }, (_, i) => {
          const tier = i + 1, available = tier <= unlocked;
          return { tier, requiredXp: tier * XP_PER_TIER, unlocked: available,
            free: { reward: tierReward(tier, 'free'), claimed: state.pass.freeClaimed.includes(tier), claimable: available && !state.pass.freeClaimed.includes(tier) },
            premium: { reward: tierReward(tier, 'premium'), claimed: state.pass.premiumClaimed.includes(tier), claimable: available && premium === true && !state.pass.premiumClaimed.includes(tier) } };
        }) } };
  }
  function claimAttendance(state, now = Date.now(), expectedDay) {
    if (!stateValid(state)) return rejected('invalid-state');
    const today = dayKey(now); if (!today) return rejected('invalid-time');
    if (expectedDay !== undefined && (!dayValid(expectedDay) || expectedDay !== today)) return rejected('day-mismatch');
    if (state.attendance.lastDay === today) return rejected('already-claimed');
    if (state.attendance.lastDay > today) return rejected('clock-before-last-claim');
    if (state.attendance.total === MAX_ATTENDANCE) return rejected('attendance-limit');
    const nextState = clone(state), cycleDay = state.attendance.total % ATTENDANCE.length + 1, gift = ATTENDANCE[cycleDay - 1];
    nextState.attendance = { lastDay: today, total: state.attendance.total + 1 };
    const xpAdded = Math.min(ATTENDANCE_XP, MAX_XP - state.pass.xp); nextState.pass.xp += xpAdded;
    return { ok: true, nextState, dayKey: today, cycleDay, xpAdded, reward: { gold: gift.gold, shards: gift.shards } };
  }
  function xpForRun(run) {
    if (!object(run) || !idValid(run.id) || !MODES.includes(run.mode)) return null;
    if (run.mode === 'duel' || run.mode === 'coop') {
      if (run.rewardVersion === undefined && run.activeSeconds === undefined) return 0;
      if (run.rewardVersion !== 1 || !integer(run.activeSeconds, 0, 6000)
        || typeof run.elapsed !== 'number' || !Number.isFinite(run.elapsed) || run.elapsed < run.activeSeconds) return null;
      return Math.floor(Math.min(run.activeSeconds, 6000) * 15 / 60);
    }
    return run.rewardVersion === undefined && run.activeSeconds === undefined && integer(run.wave, 0, Number.MAX_SAFE_INTEGER)
      ? Math.min(run.wave, 200) * 2 : null;
  }
  // The settlement must come from PG/server settlement, not an arbitrary UI
  // payload. Durable server transactions remain the final replay protection.
  function awardRunXp(state, run, settlement) {
    if (!stateValid(state)) return rejected('invalid-state');
    if (!object(settlement) || settlement.ok !== true || typeof settlement.duplicate !== 'boolean') return rejected('unsettled-run');
    const earnedXp = xpForRun(run); if (earnedXp === null) return rejected('invalid-run');
    if (settlement.duplicate || state.xpRuns.includes(run.id)) return { ok: true, duplicate: true, nextState: clone(state), xpAdded: 0, earnedXp: 0, reward: noReward() };
    const nextState = clone(state), xpAdded = Math.min(earnedXp, MAX_XP - state.pass.xp);
    nextState.pass.xp += xpAdded; nextState.xpRuns = [run.id, ...state.xpRuns].slice(0, RUN_HISTORY);
    return { ok: true, duplicate: false, nextState, xpAdded, earnedXp, reward: noReward() };
  }
  function claimPass(state, options = {}) {
    if (!stateValid(state)) return rejected('invalid-state');
    if (!object(options)) return rejected('invalid-tier');
    const { tier, track, premium = false } = options;
    const reward = tierReward(tier, track); if (!reward) return rejected('invalid-tier');
    if (tier * XP_PER_TIER > state.pass.xp) return rejected('tier-locked');
    if (track === 'premium' && premium !== true) return rejected('premium-required');
    const key = track === 'free' ? 'freeClaimed' : 'premiumClaimed';
    if (state.pass[key].includes(tier)) return rejected('already-claimed');
    const nextState = clone(state); nextState.pass[key] = [...nextState.pass[key], tier].sort((a, b) => a - b);
    return { ok: true, nextState, tier, track, xpAdded: 0, reward };
  }
  return Object.freeze({ VERSION, MAX_ATTENDANCE, RUN_HISTORY, PASS_ID, PASS_TIERS, XP_PER_TIER, MAX_XP, ATTENDANCE_XP,
    ATTENDANCE, PASS, defaultState, stateValid, sanitize, dayKey, tierReward, view, claimAttendance, xpForRun, awardRunXp, claimPass });
});

export default module.exports;
