import fs from 'node:fs';
import { createHash } from 'node:crypto';
const liveops = fs.readFileSync(new URL('../liveops-rules.js', import.meta.url), 'utf8').replace(/\r\n/g, '\n');
const liveopsHash = createHash('sha256').update(liveops).digest('hex');
const liveopsOutput = `// Generated by commerce/build.mjs; liveops-rules.js normalized SHA256 ${liveopsHash}\nconst module = { exports: {} };\n${liveops}\nexport default module.exports;\n`;
const liveopsTarget = new URL('./src/liveops-rules.mjs', import.meta.url);
if (process.argv.includes('--check')) {
  if (!fs.existsSync(liveopsTarget) || fs.readFileSync(liveopsTarget, 'utf8') !== liveopsOutput) throw Error('Run node commerce/build.mjs after liveops-rules.js changes');
} else fs.writeFileSync(liveopsTarget, liveopsOutput);
console.log(`liveops wrapper ${liveopsHash}: OK`);
if (!process.argv.includes('--liveops-only')) {
const source = fs.readFileSync(new URL('../progression.js', import.meta.url), 'utf8').replace(/\r\n/g, '\n');
const hash = createHash('sha256').update(source).digest('hex');
const rules = fs.readFileSync(new URL('../deck-rules.js', import.meta.url), 'utf8').replace(/\r\n/g, '\n');
const rulesHash = createHash('sha256').update(rules).digest('hex');
const treeRules = fs.readFileSync(new URL('../tree-rules.js', import.meta.url), 'utf8').replace(/\r\n/g, '\n');
const treeHash = createHash('sha256').update(treeRules).digest('hex');
const output = `// Generated by commerce/build.mjs; progression.js normalized SHA256 ${hash}; deck-rules.js ${rulesHash}; tree-rules.js ${treeHash}\nconst rulesModule = { exports: {} };\n(function(module) {\n${rules}\n})(rulesModule);\nconst treeModule = { exports: {} };\n(function(module, require) {\n${treeRules}\n})(treeModule, name => { if (name === './deck-rules.js') return rulesModule.exports; throw new Error('Unknown tree dependency'); });\nconst require = name => { if (name === './tree-rules.js') return treeModule.exports; if (name === './deck-rules.js') return rulesModule.exports; throw new Error('Unknown bundled module'); };\nconst module = { exports: {} };\n${source}\nexport default module.exports;\n`;
const target = new URL('./src/progression.mjs', import.meta.url);
if (process.argv.includes('--check')) {
  if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== output) throw Error('Run node commerce/build.mjs after progression.js changes');
} else { fs.mkdirSync(new URL('./src/', import.meta.url), { recursive: true }); fs.writeFileSync(target, output); }
console.log(`progression wrapper ${hash}: OK`);
}
