import fs from 'node:fs';
import { createHash } from 'node:crypto';
const source = fs.readFileSync(new URL('../progression.js', import.meta.url), 'utf8').replace(/\r\n/g, '\n');
const hash = createHash('sha256').update(source).digest('hex');
const rules = fs.readFileSync(new URL('../deck-rules.js', import.meta.url), 'utf8').replace(/\r\n/g, '\n');
const rulesHash = createHash('sha256').update(rules).digest('hex');
const output = `// Generated by commerce/build.mjs; progression.js normalized SHA256 ${hash}; deck-rules.js ${rulesHash}\nconst rulesModule = { exports: {} };\n(function(module) {\n${rules}\n})(rulesModule);\nconst require = name => { if (name === './deck-rules.js') return rulesModule.exports; throw new Error('Unknown bundled module'); };\nconst module = { exports: {} };\n${source}\nexport default module.exports;\n`;
const target = new URL('./src/progression.mjs', import.meta.url);
if (process.argv.includes('--check')) {
  if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== output) throw Error('Run node commerce/build.mjs after progression.js changes');
} else { fs.mkdirSync(new URL('./src/', import.meta.url), { recursive: true }); fs.writeFileSync(target, output); }
console.log(`progression wrapper ${hash}: OK`);
