import fs from 'node:fs';
import { createHash } from 'node:crypto';
const source = fs.readFileSync(new URL('../progression.js', import.meta.url), 'utf8').replace(/\r\n/g, '\n');
const hash = createHash('sha256').update(source).digest('hex');
const output = `// Generated by commerce/build.mjs; progression.js normalized SHA256 ${hash}\nconst module = { exports: {} };\n${source}\nexport default module.exports;\n`;
const target = new URL('./src/progression.mjs', import.meta.url);
if (process.argv.includes('--check')) {
  if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== output) throw Error('Run node commerce/build.mjs after progression.js changes');
} else { fs.mkdirSync(new URL('./src/', import.meta.url), { recursive: true }); fs.writeFileSync(target, output); }
console.log(`progression wrapper ${hash}: OK`);
