// Standalone review artifact. All sprites and the renderer are embedded so the
// exported HTML works offline and does not connect to a paid generation service.
function motionPreview(data, source) {
  return `<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dicekeep · 모션 수정 확인 v108</title>
<style>*{box-sizing:border-box}body{margin:0;background:#171918;color:#ede9d8;font:15px system-ui,sans-serif}main{max-width:1440px;margin:auto;padding:32px}h1{font-size:28px;margin:0 0 10px}p{color:#b4b9b0;line-height:1.6}header{display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap}nav{display:flex;gap:10px;align-items:center}button,select{background:#303b33;color:#f1e8c9;border:1px solid #637a66;padding:10px 15px;border-radius:6px;font:inherit;cursor:pointer}section{margin-top:32px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:18px}article{border:1px solid #39443a;border-radius:8px;overflow:hidden;background:#1e2420}h3{margin:14px 16px 4px;font-size:16px;font-weight:600}small{display:block;color:#a4ada3;margin:0 16px 8px}canvas{width:100%;height:auto;display:block}.towers{grid-template-columns:repeat(auto-fit,minmax(240px,1fr))}.labels{display:flex;justify-content:space-around;color:#b4b9b0;font-size:12px;padding:0 0 8px}.note{font-size:13px;margin-top:26px}</style>
<main><header><div><h1>주사위 성채 · 상체 왜곡 제거 v108</h1><p>몬스터의 상체 왜곡을 제거했습니다. 왼쪽은 원본, 오른쪽은 현재 적용 상태입니다.</p></div><nav><button id="pause">일시정지</button><select id="view" aria-label="이동 방향"><option value="side">옆모습</option><option value="front">앞모습</option><option value="back">뒷모습</option></select><select id="speed" aria-label="재생 속도"><option value="1">기본 속도</option><option value=".5">절반 속도</option></select></nav></header>
<section><h2>몬스터와 보스</h2><div class="grid" id="actors"></div></section><section><h2>타워 공격과 명중 효과</h2><p>건물의 받침은 고정하고, 포신·마력 장치와 발사 효과를 움직입니다. 효과는 실제 판정과 별도로 그립니다.</p><div class="grid towers" id="towers"></div></section><p class="note">몬스터 양쪽은 동일한 원본 동작을 사용합니다. 타워는 이전 공격 표현과 현재 효과를 비교합니다. 몬스터의 표시 크기는 비교하기 쉽게 통일했습니다. 생성 서비스나 추가 결제 없이 브라우저에서 재생됩니다.</p></main>
<script>${source}</script><script>
const DATA=${JSON.stringify(data).replace(/</g, '\\u003c')};
const images=new Map();async function img(src){if(images.has(src))return images.get(src);const im=new Image();im.src=src;await im.decode();images.set(src,im);return im;}
let time=0,paused=false,last=0;window.setPreviewTime=t=>{time=t;paused=true;render();};
document.getElementById('pause').onclick=()=>{paused=!paused;document.getElementById('pause').textContent=paused?'재생':'일시정지';};
function panel(parent,title,note,w,h){const a=document.createElement('article');a.innerHTML='<h3>'+title+'</h3><small>'+note+'</small><canvas width="'+w+'" height="'+h+'"></canvas><div class="labels"><span>원본</span><span>현재</span></div>';document.getElementById(parent).append(a);return a.querySelector('canvas');}
for(const e of DATA.actors)e.canvas=panel('actors',e.name,e.id+' · '+({legged:'보행',flight:'비행',float:'부유',slither:'기어가기'}[e.gait]||e.gait),600,300);
for(const t of DATA.towers)t.canvas=panel('towers',t.name,DKMOTION.family(t.face),480,280);
function ground(g,w,h){g.fillStyle='#222c25';g.fillRect(0,0,w,h);g.strokeStyle='#465246';g.lineWidth=1;g.beginPath();g.moveTo(12,h-45);g.lineTo(w-12,h-45);g.moveTo(w/2,15);g.lineTo(w/2,h-20);g.stroke();}
function render(){const view=document.getElementById('view').value,cycle=1.3,phase=(time/cycle)%1;
 for(const e of DATA.actors){const v=e.views[view],frame=v.loaded[Math.floor(phase*v.loaded.length)],g=e.canvas.getContext('2d');ground(g,600,300);const scale=Math.min((e.gait==='flight'?170:190)/v.referenceHeight,244/(v.bounds[2]-v.bounds[0]),210/(v.bounds[3]-v.bounds[1])),height=scale*v.referenceHeight,place={x:-v.pivot[0]*scale,y:-v.pivot[1]*scale,w:v.cell*scale,h:v.cell*scale};
  for(let side=0;side<2;side++){g.save();g.translate((side?450:150)-((v.bounds[0]+v.bounds[2])/2-v.pivot[0])*scale,255);if(side)DKMOTION.paintEnemy(g,frame,place);else g.drawImage(frame,place.x,place.y,place.w,place.h);g.restore();}}
 for(const t of DATA.towers){const g=t.canvas.getContext('2d');ground(g,480,280);const period=1.35,age=(time%period),firing=age<.44,sp={...t,cv:t.loaded},tower={face:t.face,def:{color:DKMOTION.COLORS[DKMOTION.family(t.face)]},x:0,y:-6,shotSerial:Math.floor(time/period)+1,attackAge:age,attackAim:-.75,cd:period-age};
  for(let side=0;side<2;side++){g.save();g.translate(side?330:110,235);g.scale(1.55,1.55);if(side)DKMOTION.paintTower(g,tower,sp,t.port);else{const k=Math.max(0,1-age/.37)**2;g.scale(1+k*.07,1-k*.09);g.drawImage(t.loaded,-t.cx,-t.baseY);}g.restore();}
  for(let side=0;side<2;side++){
    const origin=side?330:110,at=side?DKMOTION.emitter(tower,sp,t.port):{x:0,y:-70},start={x:origin+at.x*1.55,y:235+at.y*1.55},end={x:origin+95,y:40},angle=Math.atan2(end.y-start.y,end.x-start.x);
    if(t.face===1||t.face===5){if(age<.16){const im=DATA.legacy[t.face===1?'laserBeam':'lightningArc'].loaded[0];if(im){g.save();g.translate(start.x,start.y);g.rotate(angle);g.globalAlpha=1-age/.16;g.drawImage(im,0,-6,Math.hypot(end.x-start.x,end.y-start.y),12);g.restore();}if(side)DKMOTION.paintImpact(g,{kind:'combatHit',family:DKMOTION.family(t.face),x:end.x,y:end.y,size:30,t:age,dur:.25,seed:t.face});}continue;}
    if(!firing)continue;const u=Math.min(1,age/.23),p={src:{face:t.face},visualAge:age,rot:angle,spin:age*13,trail:Array.from({length:5},(_,i)=>{const a=Math.max(0,u-(4-i)*.055);return{x:start.x+(end.x-start.x)*a,y:start.y+(end.y-start.y)*a};})},pos={x:start.x+(end.x-start.x)*u,y:start.y+(end.y-start.y)*u};
    if(side){if(u<1)DKMOTION.paintProjectile(g,p,pos);else DKMOTION.paintImpact(g,{kind:'combatHit',family:DKMOTION.family(t.face),x:end.x,y:end.y,size:48,t:age-.23,dur:.3,seed:t.face});}
    else if(u<1){const key=t.face===2?'shell':t.face===3?'bolt':t.face===4?'frostShard':'dieBomb',im=DATA.legacy[key].loaded[0];g.save();g.translate(pos.x,pos.y);g.rotate(t.face>=6?age*13:angle);if(im)g.drawImage(im,-11,-11*im.height/im.width,22,22*im.height/im.width);g.restore();}
    else{const key=t.face===2?'cannonBlast':t.face===3?'arcaneBurst':t.face===4?'frostBurst':'dieExplode',frames=DATA.legacy[key].loaded,im=frames[Math.min(frames.length-1,Math.floor((age-.23)/.3*frames.length))];if(im){g.save();g.globalAlpha=1-(age-.23);g.drawImage(im,end.x-24,end.y-24,48,48);g.restore();}}
  }
 }}
(async()=>{for(const e of DATA.actors)for(const v of Object.values(e.views))v.loaded=await Promise.all(v.frames.map(img));for(const t of DATA.towers)t.loaded=await img(t.image);for(const a of Object.values(DATA.legacy))a.loaded=await Promise.all(a.map(img));window.previewReady=true;requestAnimationFrame(function frame(ts){if(!paused)time+=(last?(ts-last)/1000:0)*Number(document.getElementById('speed').value);last=ts;render();requestAnimationFrame(frame);});})();
</script></html>`;
}
module.exports = { motionPreview };
